name: Deploy to Hugging Face Space

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install git-lfs
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Configure git user
        run: |
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name  "github-actions"

      - name: Push this repo to the HF Space
        env:
          HF_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          set -e
          git remote add hf https://huggingface.co/spaces/ananyaxgarg/lisa-api
          git config --global credential.helper store
          printf "https://user:$HF_TOKEN@huggingface.co\n" > ~/.git-credentials
          git push hf HEAD:main --force
