name: Deploy to Hugging Face Space (Hub upload)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Install huggingface_hub
        run: |
          python -m pip install --upgrade pip
          pip install "huggingface_hub>=0.24.0"

      - name: Upload to HF Space via API (handles LFS automatically)
        env:
          HF_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          python - <<'PY'
          import os
          from huggingface_hub import HfApi

          HF_TOKEN = os.environ["HF_TOKEN"]
          REPO_ID = "ananyaxgarg/lisa-api"   # Space name == lisa-api
          api = HfApi(token=HF_TOKEN)

          # Ensure the Space exists and is Docker
          api.create_repo(
              repo_id=REPO_ID,
              repo_type="space",
              space_sdk="docker",
              private=False,
              exist_ok=True,
          )

          # Upload the whole repo (models in PILOT/, code, Dockerfile, etc.)
          api.upload_folder(
              repo_id=REPO_ID,
              repo_type="space",
              folder_path=".",
              path_in_repo=".",
              commit_message="Deploy from GitHub Actions (hub upload)",
              ignore_patterns=[".git*", ".github/*", "__pycache__/*"]
          )
          print("Uploaded to Space:", REPO_ID)
          PY
